export const constants = {
  props: {
    EXPIRED_DAY: 3,
    SING_UP_ADMINISTRATOR: "SING_UP_ADMINISTRATOR",
  },
  errorMessage: {
    ADMINISTRATOR_NOT_FOUND: {
      errorCode: "ADMINISTRATOR_NOT_FOUND",
    },
    ADMINISTRATOR_CONFLICT_EMAIL: { errorcode: "ADMINISTRATOR_CONFLICT_EMAIL" },
    ADMINISTRATOR_NOT_MATCH_PASSWORD: {
      errorCode: "ADMINISTRATOR_NOT_MATCH_PASSWORD",
    },
  },
};
